export const EMOJI_MAP = {
  anna: '👸',
  bam: '🦇',
  chase: '🐕',
  daniel: '🐯',
  elmo: '🔴',
  fuli: '🐆',
  goofy: '🐶',
  house: '🏠',
  icecream: '🍦',
  jj: '👶',
  kion: '🦁',
  lightning: '🏎️',
  marshall: '🐕‍🦺',
  nemo: '🐠',
  olaf: '⛄',
  peppa: '🐷',
  elsa: '👑',
  rubble: '🐶',
  skye: '🐩',
  thomas: '🚂',
  umbrella: '☂️',
  violin: '🎻',
  watermelon: '🍉',
  xylophone: '🎵',
  yoyo: '🪀',
  zuma: '🏄',
};

export const WORD_MAP = {
  anna: 'Anna',
  bam: 'Bam',
  chase: 'Chase',
  daniel: 'Daniel',
  elmo: 'Elmo',
  fuli: 'Fuli',
  goofy: 'Goofy',
  house: 'House',
  icecream: 'Ice Cream',
  jj: 'JJ',
  kion: 'Kion',
  lightning: 'Lightning',
  marshall: 'Marshall',
  nemo: 'Nemo',
  olaf: 'Olaf',
  peppa: 'Peppa',
  elsa: 'Queen Elsa',
  rubble: 'Rubble',
  skye: 'Skye',
  thomas: 'Thomas',
  umbrella: 'Umbrella',
  violin: 'Violin',
  watermelon: 'Watermelon',
  xylophone: 'Xylophone',
  yoyo: 'Yoyo',
  zuma: 'Zuma',
};

export function getImageUrl(character) {
  return `/images/letters/${character.toUpperCase()}.png`;
}
