export const EMOJI_MAP = {
  apple: '🍎',
  ball: '⚾',
  cat: '🐱',
  dog: '🐕',
  elephant: '🥚',
  fish: '🐟',
  grape: '🍇',
  hat: '🏠',
  igloo: '🍦',
  jar: '🧃',
  kite: '🪁',
  lion: '🍋',
  moon: '🌙',
  nest: '👃',
  orange: '🍊',
  pig: '🐷',
  queen: '👸',
  rain: '🌈',
  sun: '⭐',
  tree: '🌳',
  umbrella: '☂️',
  van: '🎻',
  whale: '🍉',
  xylophone: '❌',
  yak: '🪀',
  zebra: '🦓',
};

export const WORD_MAP = {
  apple: 'Apple',
  ball: 'Ball',
  cat: 'Cat',
  dog: 'Dog',
  elephant: 'Egg',
  fish: 'Fish',
  grape: 'Grapes',
  hat: 'House',
  igloo: 'Ice Cream',
  jar: 'Juice',
  kite: 'Kite',
  lion: 'Lemon',
  moon: 'Moon',
  nest: 'Nose',
  orange: 'Orange',
  pig: 'Pig',
  queen: 'Queen',
  rain: 'Rainbow',
  sun: 'Star',
  tree: 'Tree',
  umbrella: 'Umbrella',
  van: 'Violin',
  whale: 'Watermelon',
  xylophone: 'X',
  yak: 'Yo-Yo',
  zebra: 'Zebra',
};
